### ISSUE TITLE
Not getting connected to external memcache server.

### ISSUE THREAD

**Issue by satheshhmax** [petergoldstein/dalli#535] opened 2015-05-11 12:42 UTC
I'm having an rails 3.0.X application and trying to add dalli for it. memcache is running in a different server and i want my app to use that. So i configured in my config/initializers/session_store.rb file as below

```ruby
require 'action_dispatch/middleware/session/dalli_store'
Rails.application.config.session_store :dalli_store, :memcache_server => ['DifferentServer.com:11211'], :namespace => 'sessions', :key => '_session', :expire_after => 30.days
```

But still the application is trying to connect the local machine memcache. 
@servers=["127.0.0.1:11211"]

```ruby
irb(main):003:0> Rails.cache
=> #<ActiveSupport::Cache::DalliStore:0x00000005182810 @options={:compress=>nil}, @data=#<Dalli::Client:0x00000004f61f68 @servers=["127.0.0.1:11211"], @options={:compress=>nil}, @ring=nil>, @thread_local_key=:active_support_cache_dalli_store_local_cache_42734600, @middleware=ActiveSupport::Cache::Strategy::LocalCache>
```

My expected result should be @servers=["DifferentServer.com:11211"]

**Comment by bmartel** [comment] 2015-05-17 07:35
I'm also seeing the same problem in a rails 4.1 app, running within docker containers. 
```
        config.cache_store = :dalli_store, ENV["CACHE_HOST"],
        {
            :namespace => 'MyAppNamepace',
            :expires_in => 1.day,
            :compress => true,
            :username => ENV["MEMCACHED_USER"],
            :password => ENV["MEMCACHED_PASS"],
        }
```
My **CACHE_HOST** is just a reference to the host that is generated and set by the docker container, which is just some 172.17.x.x/16 ip bound to the name of the container.

The host for my memcached container gets ignored and the web container ends up with the same above reference as @satheshhmax, only "127.0.0.1:11211".

**Comment by paulmenzel** [comment] 2015-07-23 09:26
I am having the same issue with Dalli 2.6.4 and Rails 3.2.22.

```
$ grep dalli config/environments/production.rb
  config.cache_store = :dalli_store, ['memcached']
$ grep memcached /etc/hosts 
172.17.0.155    memcached memcached
$ bundle exec rails c
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
==> Loading production environment (Rails 3.2.22)
irb(main):001:0> Rails.env
=> "production"
irb(main):002:0> Dalli::Client.new
=> #<Dalli::Client:0x0000000a511cb0 @servers=["127.0.0.1:11211"], @options={}, @ring=nil>
```

**Comment by paulmenzel** [comment] 2015-07-23 09:28
@satheshhmax, @bmartel, were you able to find a solution for this problem?

**Comment by paulmenzel** [comment] 2015-07-23 13:02
Using `Dalli::Client.new` is a red herring and probably does not use the Rails setting intentionally. Running `Rails.cache` as @satheshhmax did, the server seems to be set correctly.

```
$ bundle exec gem list dalli

*** LOCAL GEMS ***

dalli (2.6.4)
$ bundle exec rails c
[…]
==> Loading production environment (Rails 3.2.22)
irb(main):001:0> Rails.cache
=> #<ActiveSupport::Cache::DalliStore:0x00000008a5b970 @options={:compress=>nil}, @raise_errors=false, @data=#<Dalli::Client:0x00000008a5b880 @servers=["memcached"], @options={:compress=>nil}, @ring=nil>, …
irb(main):002:0> Dalli::Client.new
=> #<Dalli::Client:0x0000000b23fce8 @servers=["127.0.0.1:11211"], @options={}, @ring=nil>
```

So, I have no idea, what wasn’t configured correctly on my system, but it seems to work with Rails 3.2.22 and Dalli 2.6.4 (and Dalli 2.7.4, tried during analyzing the issue).

**Comment by satheshhmax** [comment] 2015-07-23 19:13
@paulmenzel  I finally ended up adding a dirty patch to my application, by overriding dalli method and hard coding my server URL i need, instead of localhost:11211.

**Comment by petergoldstein** [comment] 2015-12-07 09:09
Closing, as I can't reproduce.  Please reopen if you have a reproducible test case.

**Closed by petergoldstein** 2015-12-07 09:09 UTC

**Comment by wedgemartin** [comment] 2016-03-21 14:57
I see the same issue.  Rails 4.  Completely ignore any host settings and insists on trying to connect to localhost.

**Comment by lcoq** [comment] 2016-03-29 17:00
:+1: Same issue too with Rails 4.1.1

**Comment by wmuengineer** [comment] 2016-12-09 20:17
For Ruby 2.3.3 and Rails 4.2.1 setting the `MEMCACHE_SERVERS` ENV variable did nothing. Dalii keep trying to connect to localhost.
