### ISSUE TITLE
session_store: rails 5 support

### ISSUE THREAD

**Issue by m0n9oose** [petergoldstein/dalli#613] opened 2016-04-19 12:00 UTC
I'm trying to use dalli as session storage with rails 5.0.0.beta3, and getting error

```
Started GET "/sign_in" for 192.168.1.1 at 2016-04-19 14:55:29 +0000

RuntimeError (#find_session not implemented.)
```

It seems now dalli works fine with stable 1.x rack, but rack 2.0 implements new methods for session `#find_session` instead of old one `#get_session`

**Comment by petergoldstein** [comment] 2016-04-19 16:01
What version of Dalli are you using?  Is this a problem when using the master branch?

**Comment by m0n9oose** [comment] 2016-04-19 16:03
tried version '2.7.6' and master branch too.

**Comment by petergoldstein** [comment] 2016-04-19 16:06
That's a little surprising, as master was updated for Rails 5 compatibility and even includes a Rails 5 prerelease in its test suite.  I'll need to review - it would be helpful if you double checked your master results

**Comment by m0n9oose** [comment] 2016-04-19 16:08
yeah, a saw few last commits, and was pretty sure, that version from master branch should work as expected, but still getting this error ( thank you very much for your help

**Comment by petergoldstein** [comment] 2016-04-20 06:52
@m0n9oose  Do you have a test app you can share?  I'm unable to reproduce the problem.

**Comment by m0n9oose** [comment] 2016-04-20 07:53
sure, here is the link https://github.com/m0n9oose/dalli_test_app

rails 5.0.0.beta3 blank app, with `dalli` from master branch.

**Comment by zloydadka** [comment] 2016-04-20 18:01
@petergoldstein i have same problem!
i think this problem occurred by new rack 2.0 implementation.

**Comment by zhirayrized** [comment] 2016-04-20 18:11
@petergoldstein i have same problem!
i think this problem occurred by new rack 2.0 implementation.

https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L379

**Comment by petergoldstein** [comment] 2016-04-22 16:01
So aside from a Ruby 2.3 frozen string issue (now fixed in dalli master), I confirmed that this was a misconfiguration of the test application.  Specifically, the old pre-Rails 4 instructions were being used in the test app.  I will update these instructions for clarify some time soon.

To get things working in Rails 5, you need to do two things:

1. Update the value of `config.cache_store` in your environment configuration to be :dalli_store
2. Set the `config.session_store` values to `ActionDispatch::Session::CacheStore` with whatever options you'd like 

You can find a working version of your test app here - https://github.com/petergoldstein/dalli_test_app

As a side note, you need to modify the session to force it to write and read to Dalli.  In my version of your test app I just had the update occur in the view for simplicity's sake.

**Closed by petergoldstein** 2016-04-22 16:01 UTC

**Comment by klymacs** [comment] 2016-04-28 21:47
This worked for me:

```
module ActionDispatch
  module Session
    class DalliStore < AbstractStore
      alias_method :find_session, :get_session
      alias_method :write_session, :set_session
    end
  end
end
```

**Comment by andrewkendall** [comment] 2016-07-04 20:10
I'm also running in to this issue since moving to Rails 5. I'm using the legacy code in my session_store.rb

```
require 'action_dispatch/middleware/session/dalli_store'
Rails.application.config.session_store :dalli_store, memcache_server: 'sessions.myapp.com:11211', namespace: 'sessions', username: 'sessions', password: 'xxx', keepalive: true, key: 'xxx'
```

I understand that the suggestion is to move to using
```
Rails.application.config.session_store ActionDispatch::Session::CacheStore, :expire_after => 20.minutes
```

From what I can see the latest method uses the connection defined by config.cache_store in the environment file.

With the apps I'm working on we currently have two separate memcached stores sessions.myapp.com and application.myapp.com so production.rb is set up as

```
config.cache_store = :dalli_store, 'application.myapp.com:11211', { namespace: 'app', compress: true, username: 'application', password: 'xxx', expires_in: 2592000, keepalive: true }
```

Is there a new suggested way to handle separate locations for application and session storage?

**Comment by petergoldstein** [comment] 2016-07-04 20:41
While I haven't done it in production myself, you should be able to pass in a Dalli::Client in the session_store configuration.  Something like:

    Rails.application.config.session_store ActionDispatch::Session::CacheStore, expire_after: 20.minutes, cache: Dalli::Client.new(...)

**Comment by andrewkendall** [comment] 2016-07-04 20:44
Excellent. I'll give that a try and report back :) Thank you for the fast reply!

**Comment by andrewkendall** [comment] 2016-07-05 12:54
I've now tested using:

```
Rails.application.config.session_store ActionDispatch::Session::CacheStore, expire_after: 20.minutes, cache: Dalli::Client.new('localhost:11211')
```
Result is "undefined method `write' for #<Dalli::Client:0x007f800a391f48>" - https://dl.dropboxusercontent.com/u/1043974/Images/4e509625-3445-4258-aebb-a7d808709c8f.png

I thought I was getting somewhere by using:

```
Rails.application.config.session_store :mem_cache_store, memcache_server: 'localhost:11211'
```
That works in my testing environment using an unprotected Memcached store.

Am I correct in thinking that :mem_cache_store still uses Dalli?

With my apps the production session store is password protected. I've tried the following:

```
Rails.application.config.session_store :mem_cache_store, memcache_server: 'sessions.myapp.com:11211',  namespace: 'sessions', username: 'sessions', password: 'xxx', key: 'xxx'
```

With that configuration I'm not able to connect, so I assume that I'm passing the username and password in the wrong way.

Any suggestions are appreciated.

**Comment by andrewkendall** [comment] 2016-07-11 11:42
For anyone looking for an answer to this, this is what I'm now using in production in session_store.rb:

```
Rails.application.config.session_store ActionDispatch::Session::CacheStore, cache: ActiveSupport::Cache::MemCacheStore.new('sessions.myapp.com:11211', { namespace: 'sessions', username: 'sessions', password: 'xxx', keepalive: true, key: 'xxx' })
```

**Comment by geniousli** [comment] 2017-01-17 03:43
@andrewkendall @petergoldstein  why not write this to readme,  as the old rails guides not the same as rails5, and this can let someone easier

**Comment by mattruzicka** [comment] 2018-03-14 18:12
@andrewkendall's code above didn't work for me with the 2.7.6 release. It does seem to work when I use the master branch.

**Comment by chewi** [comment] 2018-08-30 09:38
I don't think @andrewkendall's last suggest would actually use Dalli. This works for me.

```ruby
require 'active_support/cache/dalli_store'
Rails.application.config.session_store ActionDispatch::Session::CacheStore, cache: ActiveSupport::Cache::DalliStore.new('sessions.myapp.com:11211', { namespace: 'sessions', username: 'sessions', password: 'xxx', keepalive: true, key: 'xxx' })
```
